[Interface]
# Address = 169.254.0.4/26
PrivateKey =
# publicKey =
ListenPort = 51820

# Dos
[Peer]
PublicKey =
Endpoint =
AllowedIPs = 10.0.1.0/24,169.254.0.5/32
PersistentKeepAlive = 10

# Neo
[Peer]
PublicKey =
Endpoint =
AllowedIPs = 10.0.3.0/24,169.254.0.1/32
PersistentKeepAlive = 10

# TB Lugia
[Peer]
PublicKey =
Endpoint =
AllowedIPs = 10.0.4.0/24,169.254.0.3/32
PersistentKeepAlive = 10

