# Recursive mode DNS makes Unbound donwloads lists of DNS entries from the TLD dns servers directly.
# In order to do this we will need first provide a hint of where these servers are:
#
# curl -o /etc/unbound/conf.d/recursive-raw.hints "https://www.internic.net/domain/named.root"
#
# I've provided a systemd timer that updates this file on the first of every month.
# You can find it at unbound-root-hints.timer running unbound-root-hints.service.
#
# Additional options can be found here: https://github.com/anudeepND/pihole-unbound
server:
  root-hints: "/etc/unbound/conf.d/recursive-raw.hints"

